car='subaru'
print('Is Car == subaru? I predict True')
print(car=='subaru')
print('\nIs Car == audi? I predict False')
print(car=='audi')
print('\n')
print('Is Car == subaru? I predict True')
print(car.lower()=='Subaru'.lower())
print('\nIs Car == subaru? I predict False')
print(car=='Subaru')
print('\n')
number=10
print('Is number == 10? I predict True')
print(number==10)
print('Is number ==20? I predict False')
print(number==20)
print('\n')
print('Is number !=30? I predict True')
print(number!=30)
print('Is number !=10? I predict False')
print(number!=10)
print('\n')
print('Is number >= 30? I predict True')
print(number>=30)
print('Is number =!10? I predict False')
print(number>=10)
print('\n')
print('Is number >= 30? I predict True')
print(number<=30)
print('Is number =!10? I predict False')
print(number<=10)
print('\n')
print('Is number >= 5 and number <= 20 ? I predict True')
print(number >= 5 and number <= 20)
print('Is number >= 5 and number <= 9 predict False')
print(number >= 5 and number <= 9)
print('\n')
cooks=['Спагетти','Котлеты','Салат Цезарь','Рис','Грибной суп']
print('Голубцы' in cooks)
print('Голубцы' not in cooks)