from random import randint
class Die:
    def __init__(self,sides=6):
        self.sides = sides   # сохраняем в атрибут
    def  roll_die(self):
        value = randint(1, self.sides)
        print(value)
st1=Die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1=Die(10)
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1=Die(20)
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
st1.roll_die()
